<div class="w3-panel w3-theme-l1">
    <h3><i class="fa fa-anchor"></i> Anchors</h3>
    <p>Click the link below to go the anchor #3. The anchor is display by calling the <a href="https://mobile.znetdk.fr/js-api#z4m-jsapi-content-gotoanchor" target="_blank" rel="noopener">znetdkMobile.content.goToAnchor()</a> JS method.</p>
</div>
<p><a href="javascript:void(0)" onclick="znetdkMobile.content.goToAnchor('anchor3');">Go to page anchor #3</a></p>
<h3 id="anchor1">Anchor 1</h3>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse aliquet ornare nulla ut varius. Etiam dui nulla, scelerisque eu pulvinar in, lacinia in purus. Praesent tempus vehicula turpis id semper. Praesent ultricies nisl purus, sit amet mattis turpis placerat pellentesque. Sed a consequat mi. Praesent id mauris ut tortor dapibus tempor id vitae magna. Sed suscipit diam a dapibus suscipit. Aliquam non mauris magna. Maecenas ac tortor ultricies lectus vestibulum convallis. Integer non mauris ac mi efficitur egestas. Nunc quis leo eget lectus imperdiet sollicitudin vitae vel augue. Sed et odio odio. Donec accumsan orci ut ullamcorper placerat. Donec ultrices erat id tempor commodo. Quisque at consectetur ex. Suspendisse nec augue at massa aliquam porttitor.</p>
<p>Phasellus venenatis, velit in luctus tincidunt, diam eros ultricies elit, sit amet fringilla libero quam nec urna. Etiam at mi maximus, maximus enim vel, consequat mauris. Pellentesque nec odio est. Quisque vel pharetra enim, id mollis tellus. Nullam et ultrices elit. In lorem leo, pellentesque nec lectus quis, venenatis gravida purus. Vestibulum egestas libero at ultrices congue. Sed eget urna sed ex dictum sollicitudin. Suspendisse quis molestie nisi, at malesuada sapien. Mauris lacinia maximus pretium. Cras vel est libero. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut non accumsan dolor. Nulla eleifend faucibus elit sit amet consectetur.</p>
<p>Vestibulum et facilisis ligula. Donec maximus enim non pellentesque aliquam. Nullam hendrerit neque in molestie ultrices. In id libero consectetur, ullamcorper urna et, hendrerit ipsum. Etiam dapibus, augue ut fermentum pulvinar, turpis nisi porta nibh, vel tincidunt elit arcu quis felis. In suscipit elit a luctus pretium. Nullam dictum, mi vel viverra mollis, orci massa pellentesque lectus, in vulputate orci mi et leo. In gravida euismod ligula in tincidunt.</p>
<p>Ut blandit nibh vel quam ullamcorper, nec suscipit diam viverra. Sed placerat massa ut tincidunt venenatis. Ut venenatis lorem eget hendrerit volutpat. Duis fermentum libero id lacus pellentesque bibendum. Donec non fringilla urna. Aenean porttitor, ipsum euismod suscipit facilisis, ipsum neque porta justo, et auctor neque eros a orci. Quisque tincidunt justo convallis cursus lacinia. Pellentesque et justo id orci porttitor convallis. In sit amet est non nibh auctor sollicitudin. Ut varius justo sed elementum tincidunt. Nunc mollis interdum ex eu ultrices.</p>
<p>Pellentesque elementum sem ut ullamcorper imperdiet. Donec magna mi, laoreet et posuere ut, porttitor elementum libero. Morbi est velit, porttitor eu velit vitae, ornare mollis tellus. Vestibulum tristique facilisis auctor. Cras lacus nibh, lobortis quis tellus sed, suscipit gravida mauris. Donec pulvinar egestas neque, id varius dui. Nulla fringilla mauris at elementum ultrices. Nullam at eleifend felis. Vestibulum efficitur congue orci a pharetra. Donec fringilla aliquet orci, vitae commodo felis fermentum ut. Donec mattis luctus imperdiet. Duis elementum placerat lacus varius molestie. Maecenas volutpat quam et risus interdum, sed vehicula lectus lobortis.</p>
<h3 id="anchor2">Anchor 2</h3>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse aliquet ornare nulla ut varius. Etiam dui nulla, scelerisque eu pulvinar in, lacinia in purus. Praesent tempus vehicula turpis id semper. Praesent ultricies nisl purus, sit amet mattis turpis placerat pellentesque. Sed a consequat mi. Praesent id mauris ut tortor dapibus tempor id vitae magna. Sed suscipit diam a dapibus suscipit. Aliquam non mauris magna. Maecenas ac tortor ultricies lectus vestibulum convallis. Integer non mauris ac mi efficitur egestas. Nunc quis leo eget lectus imperdiet sollicitudin vitae vel augue. Sed et odio odio. Donec accumsan orci ut ullamcorper placerat. Donec ultrices erat id tempor commodo. Quisque at consectetur ex. Suspendisse nec augue at massa aliquam porttitor.</p>
<p>Phasellus venenatis, velit in luctus tincidunt, diam eros ultricies elit, sit amet fringilla libero quam nec urna. Etiam at mi maximus, maximus enim vel, consequat mauris. Pellentesque nec odio est. Quisque vel pharetra enim, id mollis tellus. Nullam et ultrices elit. In lorem leo, pellentesque nec lectus quis, venenatis gravida purus. Vestibulum egestas libero at ultrices congue. Sed eget urna sed ex dictum sollicitudin. Suspendisse quis molestie nisi, at malesuada sapien. Mauris lacinia maximus pretium. Cras vel est libero. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut non accumsan dolor. Nulla eleifend faucibus elit sit amet consectetur.</p>
<p>Vestibulum et facilisis ligula. Donec maximus enim non pellentesque aliquam. Nullam hendrerit neque in molestie ultrices. In id libero consectetur, ullamcorper urna et, hendrerit ipsum. Etiam dapibus, augue ut fermentum pulvinar, turpis nisi porta nibh, vel tincidunt elit arcu quis felis. In suscipit elit a luctus pretium. Nullam dictum, mi vel viverra mollis, orci massa pellentesque lectus, in vulputate orci mi et leo. In gravida euismod ligula in tincidunt.</p>
<p>Ut blandit nibh vel quam ullamcorper, nec suscipit diam viverra. Sed placerat massa ut tincidunt venenatis. Ut venenatis lorem eget hendrerit volutpat. Duis fermentum libero id lacus pellentesque bibendum. Donec non fringilla urna. Aenean porttitor, ipsum euismod suscipit facilisis, ipsum neque porta justo, et auctor neque eros a orci. Quisque tincidunt justo convallis cursus lacinia. Pellentesque et justo id orci porttitor convallis. In sit amet est non nibh auctor sollicitudin. Ut varius justo sed elementum tincidunt. Nunc mollis interdum ex eu ultrices.</p>
<p>Pellentesque elementum sem ut ullamcorper imperdiet. Donec magna mi, laoreet et posuere ut, porttitor elementum libero. Morbi est velit, porttitor eu velit vitae, ornare mollis tellus. Vestibulum tristique facilisis auctor. Cras lacus nibh, lobortis quis tellus sed, suscipit gravida mauris. Donec pulvinar egestas neque, id varius dui. Nulla fringilla mauris at elementum ultrices. Nullam at eleifend felis. Vestibulum efficitur congue orci a pharetra. Donec fringilla aliquet orci, vitae commodo felis fermentum ut. Donec mattis luctus imperdiet. Duis elementum placerat lacus varius molestie. Maecenas volutpat quam et risus interdum, sed vehicula lectus lobortis.</p>
<h3 id="anchor3">Anchor 3</h3>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse aliquet ornare nulla ut varius. Etiam dui nulla, scelerisque eu pulvinar in, lacinia in purus. Praesent tempus vehicula turpis id semper. Praesent ultricies nisl purus, sit amet mattis turpis placerat pellentesque. Sed a consequat mi. Praesent id mauris ut tortor dapibus tempor id vitae magna. Sed suscipit diam a dapibus suscipit. Aliquam non mauris magna. Maecenas ac tortor ultricies lectus vestibulum convallis. Integer non mauris ac mi efficitur egestas. Nunc quis leo eget lectus imperdiet sollicitudin vitae vel augue. Sed et odio odio. Donec accumsan orci ut ullamcorper placerat. Donec ultrices erat id tempor commodo. Quisque at consectetur ex. Suspendisse nec augue at massa aliquam porttitor.</p>
<p>Phasellus venenatis, velit in luctus tincidunt, diam eros ultricies elit, sit amet fringilla libero quam nec urna. Etiam at mi maximus, maximus enim vel, consequat mauris. Pellentesque nec odio est. Quisque vel pharetra enim, id mollis tellus. Nullam et ultrices elit. In lorem leo, pellentesque nec lectus quis, venenatis gravida purus. Vestibulum egestas libero at ultrices congue. Sed eget urna sed ex dictum sollicitudin. Suspendisse quis molestie nisi, at malesuada sapien. Mauris lacinia maximus pretium. Cras vel est libero. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut non accumsan dolor. Nulla eleifend faucibus elit sit amet consectetur.</p>
<p>Vestibulum et facilisis ligula. Donec maximus enim non pellentesque aliquam. Nullam hendrerit neque in molestie ultrices. In id libero consectetur, ullamcorper urna et, hendrerit ipsum. Etiam dapibus, augue ut fermentum pulvinar, turpis nisi porta nibh, vel tincidunt elit arcu quis felis. In suscipit elit a luctus pretium. Nullam dictum, mi vel viverra mollis, orci massa pellentesque lectus, in vulputate orci mi et leo. In gravida euismod ligula in tincidunt.</p>
<p>Ut blandit nibh vel quam ullamcorper, nec suscipit diam viverra. Sed placerat massa ut tincidunt venenatis. Ut venenatis lorem eget hendrerit volutpat. Duis fermentum libero id lacus pellentesque bibendum. Donec non fringilla urna. Aenean porttitor, ipsum euismod suscipit facilisis, ipsum neque porta justo, et auctor neque eros a orci. Quisque tincidunt justo convallis cursus lacinia. Pellentesque et justo id orci porttitor convallis. In sit amet est non nibh auctor sollicitudin. Ut varius justo sed elementum tincidunt. Nunc mollis interdum ex eu ultrices.</p>
<p>Pellentesque elementum sem ut ullamcorper imperdiet. Donec magna mi, laoreet et posuere ut, porttitor elementum libero. Morbi est velit, porttitor eu velit vitae, ornare mollis tellus. Vestibulum tristique facilisis auctor. Cras lacus nibh, lobortis quis tellus sed, suscipit gravida mauris. Donec pulvinar egestas neque, id varius dui. Nulla fringilla mauris at elementum ultrices. Nullam at eleifend felis. Vestibulum efficitur congue orci a pharetra. Donec fringilla aliquet orci, vitae commodo felis fermentum ut. Donec mattis luctus imperdiet. Duis elementum placerat lacus varius molestie. Maecenas volutpat quam et risus interdum, sed vehicula lectus lobortis.</p>
<h3 id="anchor4">Anchor 4</h3>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse aliquet ornare nulla ut varius. Etiam dui nulla, scelerisque eu pulvinar in, lacinia in purus. Praesent tempus vehicula turpis id semper. Praesent ultricies nisl purus, sit amet mattis turpis placerat pellentesque. Sed a consequat mi. Praesent id mauris ut tortor dapibus tempor id vitae magna. Sed suscipit diam a dapibus suscipit. Aliquam non mauris magna. Maecenas ac tortor ultricies lectus vestibulum convallis. Integer non mauris ac mi efficitur egestas. Nunc quis leo eget lectus imperdiet sollicitudin vitae vel augue. Sed et odio odio. Donec accumsan orci ut ullamcorper placerat. Donec ultrices erat id tempor commodo. Quisque at consectetur ex. Suspendisse nec augue at massa aliquam porttitor.</p>
<p>Phasellus venenatis, velit in luctus tincidunt, diam eros ultricies elit, sit amet fringilla libero quam nec urna. Etiam at mi maximus, maximus enim vel, consequat mauris. Pellentesque nec odio est. Quisque vel pharetra enim, id mollis tellus. Nullam et ultrices elit. In lorem leo, pellentesque nec lectus quis, venenatis gravida purus. Vestibulum egestas libero at ultrices congue. Sed eget urna sed ex dictum sollicitudin. Suspendisse quis molestie nisi, at malesuada sapien. Mauris lacinia maximus pretium. Cras vel est libero. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut non accumsan dolor. Nulla eleifend faucibus elit sit amet consectetur.</p>
<p>Vestibulum et facilisis ligula. Donec maximus enim non pellentesque aliquam. Nullam hendrerit neque in molestie ultrices. In id libero consectetur, ullamcorper urna et, hendrerit ipsum. Etiam dapibus, augue ut fermentum pulvinar, turpis nisi porta nibh, vel tincidunt elit arcu quis felis. In suscipit elit a luctus pretium. Nullam dictum, mi vel viverra mollis, orci massa pellentesque lectus, in vulputate orci mi et leo. In gravida euismod ligula in tincidunt.</p>
<p>Ut blandit nibh vel quam ullamcorper, nec suscipit diam viverra. Sed placerat massa ut tincidunt venenatis. Ut venenatis lorem eget hendrerit volutpat. Duis fermentum libero id lacus pellentesque bibendum. Donec non fringilla urna. Aenean porttitor, ipsum euismod suscipit facilisis, ipsum neque porta justo, et auctor neque eros a orci. Quisque tincidunt justo convallis cursus lacinia. Pellentesque et justo id orci porttitor convallis. In sit amet est non nibh auctor sollicitudin. Ut varius justo sed elementum tincidunt. Nunc mollis interdum ex eu ultrices.</p>
<p>Pellentesque elementum sem ut ullamcorper imperdiet. Donec magna mi, laoreet et posuere ut, porttitor elementum libero. Morbi est velit, porttitor eu velit vitae, ornare mollis tellus. Vestibulum tristique facilisis auctor. Cras lacus nibh, lobortis quis tellus sed, suscipit gravida mauris. Donec pulvinar egestas neque, id varius dui. Nulla fringilla mauris at elementum ultrices. Nullam at eleifend felis. Vestibulum efficitur congue orci a pharetra. Donec fringilla aliquet orci, vitae commodo felis fermentum ut. Donec mattis luctus imperdiet. Duis elementum placerat lacus varius molestie. Maecenas volutpat quam et risus interdum, sed vehicula lectus lobortis.</p>
<h3 id="anchor5">Anchor 5</h3>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse aliquet ornare nulla ut varius. Etiam dui nulla, scelerisque eu pulvinar in, lacinia in purus. Praesent tempus vehicula turpis id semper. Praesent ultricies nisl purus, sit amet mattis turpis placerat pellentesque. Sed a consequat mi. Praesent id mauris ut tortor dapibus tempor id vitae magna. Sed suscipit diam a dapibus suscipit. Aliquam non mauris magna. Maecenas ac tortor ultricies lectus vestibulum convallis. Integer non mauris ac mi efficitur egestas. Nunc quis leo eget lectus imperdiet sollicitudin vitae vel augue. Sed et odio odio. Donec accumsan orci ut ullamcorper placerat. Donec ultrices erat id tempor commodo. Quisque at consectetur ex. Suspendisse nec augue at massa aliquam porttitor.</p>
<p>Phasellus venenatis, velit in luctus tincidunt, diam eros ultricies elit, sit amet fringilla libero quam nec urna. Etiam at mi maximus, maximus enim vel, consequat mauris. Pellentesque nec odio est. Quisque vel pharetra enim, id mollis tellus. Nullam et ultrices elit. In lorem leo, pellentesque nec lectus quis, venenatis gravida purus. Vestibulum egestas libero at ultrices congue. Sed eget urna sed ex dictum sollicitudin. Suspendisse quis molestie nisi, at malesuada sapien. Mauris lacinia maximus pretium. Cras vel est libero. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut non accumsan dolor. Nulla eleifend faucibus elit sit amet consectetur.</p>
<p>Vestibulum et facilisis ligula. Donec maximus enim non pellentesque aliquam. Nullam hendrerit neque in molestie ultrices. In id libero consectetur, ullamcorper urna et, hendrerit ipsum. Etiam dapibus, augue ut fermentum pulvinar, turpis nisi porta nibh, vel tincidunt elit arcu quis felis. In suscipit elit a luctus pretium. Nullam dictum, mi vel viverra mollis, orci massa pellentesque lectus, in vulputate orci mi et leo. In gravida euismod ligula in tincidunt.</p>
<p>Ut blandit nibh vel quam ullamcorper, nec suscipit diam viverra. Sed placerat massa ut tincidunt venenatis. Ut venenatis lorem eget hendrerit volutpat. Duis fermentum libero id lacus pellentesque bibendum. Donec non fringilla urna. Aenean porttitor, ipsum euismod suscipit facilisis, ipsum neque porta justo, et auctor neque eros a orci. Quisque tincidunt justo convallis cursus lacinia. Pellentesque et justo id orci porttitor convallis. In sit amet est non nibh auctor sollicitudin. Ut varius justo sed elementum tincidunt. Nunc mollis interdum ex eu ultrices.</p>
<p>Pellentesque elementum sem ut ullamcorper imperdiet. Donec magna mi, laoreet et posuere ut, porttitor elementum libero. Morbi est velit, porttitor eu velit vitae, ornare mollis tellus. Vestibulum tristique facilisis auctor. Cras lacus nibh, lobortis quis tellus sed, suscipit gravida mauris. Donec pulvinar egestas neque, id varius dui. Nulla fringilla mauris at elementum ultrices. Nullam at eleifend felis. Vestibulum efficitur congue orci a pharetra. Donec fringilla aliquet orci, vitae commodo felis fermentum ut. Donec mattis luctus imperdiet. Duis elementum placerat lacus varius molestie. Maecenas volutpat quam et risus interdum, sed vehicula lectus lobortis.</p>
<script>
    znetdkMobile.action.setScrollUpButtonForView('anchors');
</script>